chore: deploy to openshift

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -10,7 +10,7 @@ on:
       - 'stable'
 
 jobs:
-  integration-tests:
+  integration-tests-local:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -41,7 +41,7 @@ jobs:
         run: |
           docker run --name iqe --network host \
             -e IQE_TESTS_LOCAL_CONF_PATH=/iqe_settings ${{ secrets.IQE_TESTS_IMAGE }} \
-            iqe tests plugin vulnerability -k 'vmaas' --html=report.html --self-contained-html
+            iqe tests plugin vulnerability -k 'vmaas and not reconnect' --long-running --html=report.html --self-contained-html
       - run: docker-compose logs > logs
         if: always()
       - run: docker cp iqe:/iqe_venv/report.html .
@@ -50,7 +50,7 @@ jobs:
         uses: actions/upload-artifact@v1
         if: always()
         with:
-          name: test-report
+          name: test-report-local
           path: report.html
       - name: Publish logs
         uses: actions/upload-artifact@v1
@@ -58,3 +58,191 @@ jobs:
         with:
           name: docker-compose-logs
           path: logs
+
+  integration-tests-openshift:
+    runs-on: ubuntu-latest
+    env:
+      E2E_DEPLOY_PATH: "$GITHUB_WORKSPACE/e2e-deploy"
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v2
+      - name: Check out e2e-deploy
+        uses: actions/checkout@v2
+        with:
+          repository: RedHatInsights/e2e-deploy
+          token: "${{ secrets.VMAAS_BOT }}"
+          path: e2e-deploy
+      - name: Cancel previous builds
+        uses: rokroskar/workflow-run-cleanup-action@master
+        env:
+          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
+      - name: Set up Python
+        uses: actions/setup-python@v1
+        with:
+          python-version: 3.7
+      - name: Install e2e-deploy's dependencies
+        run: |
+          pip install -U pip
+          pip install -r "${{ env.E2E_DEPLOY_PATH }}/requirements.txt"
+      - name: Download oc
+        run: |
+          mkdir oc
+          curl -L https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz | tar xz -C oc --strip-components=1
+          echo "::add-path::$GITHUB_WORKSPACE/oc"
+      - name: Docker Login
+        uses: Azure/docker-login@v1
+        with:
+          username: ${{ secrets.REGISTRY_USERNAME }}
+          password: ${{ secrets.REGISTRY_PASSWORD }}
+          login-server: quay.io
+      - name: OpenShift Login
+        run: |
+          oc login "${{ secrets.OPENSHIFT_SERVER_URL }}" --token "${{ secrets.OPENSHIFT_TOKEN }}"
+          oc project vmaas-qe
+      - name: Wipe test environment
+        run: |
+          oc project vmaas-qe
+          ocdeployer wipe -f vmaas-qe -l app=vmaas
+          # make sure that DB volume is deleted
+          oc delete pvc vmaas-database-data || true
+      - name: Build VMaaS
+        run: |
+          cd ${{ env.E2E_DEPLOY_PATH }}
+          cat <<EOF > env/builder-env.yml
+          vmaas/vmaas-reposcan:
+            parameters:
+              SOURCE_REPOSITORY_REF: "${{ github.ref }}"
+              SOURCE_REPOSITORY_URL: "https://github.com/${{ github.repository }}"
+          vmaas/vmaas-webapp:
+            parameters:
+              SOURCE_REPOSITORY_REF: "${{ github.ref }}"
+              SOURCE_REPOSITORY_URL: "https://github.com/${{ github.repository }}"
+              DOCKERFILE_PATH: webapp/Dockerfile-qe
+          vmaas/vmaas-websocket:
+            parameters:
+              SOURCE_REPOSITORY_REF: "${{ github.ref }}"
+              SOURCE_REPOSITORY_URL: "https://github.com/${{ github.repository }}"
+          vmaas/vmaas-database:
+            parameters:
+              SOURCE_REPOSITORY_REF: "${{ github.ref }}"
+              SOURCE_REPOSITORY_URL: "https://github.com/${{ github.repository }}"
+          EOF
+
+          ocdeployer deploy -f --sets vmaas \
+            --template-dir buildfactory \
+            -e builder-env vmaas-qe --secrets-src-project secrets
+      - name: Deploy VMaaS
+        run: |
+          cd ${{ env.E2E_DEPLOY_PATH }}
+          ocdeployer deploy -f --sets vmaas -e vmaas-qe vmaas-qe
+      - name: Expose routes
+        run: |
+          oc project vmaas-qe
+          webapp="${{ secrets.OPENSHIFT_WEBAPP_URL }}"
+          reposcan="${{ secrets.OPENSHIFT_REPOSCAN_URL }}"
+          cat <<EOF > webapp-route.yaml
+          apiVersion: route.openshift.io/v1
+          kind: Route
+          metadata:
+            name: vmaas-webapp
+            namespace: vmaas-qe
+          spec:
+            host: ${webapp#http://}
+            port:
+              targetPort: 8080
+            to:
+              kind: Service
+              name: vmaas-webapp
+              weight: 100
+            wildcardPolicy: None
+          EOF
+
+          cat <<EOF > reposcan-route.yaml
+          apiVersion: route.openshift.io/v1
+          kind: Route
+          metadata:
+            name: vmaas-reposcan
+            namespace: vmaas-qe
+          spec:
+            host: ${reposcan#http://}
+            port:
+              targetPort: 8081
+            to:
+              kind: Service
+              name: vmaas-reposcan
+              weight: 100
+            wildcardPolicy: None
+          EOF
+
+          oc apply -f webapp-route.yaml
+          oc apply -f reposcan-route.yaml
+      - name: Start VMaaS webapp with coverage
+        run: |
+          webapp_pod="$(oc get pods | grep 'Running' | grep 'webapp' | awk '{print $1}')"
+          oc exec "${webapp_pod}" -- bash -c "coverage run main.py --source webapp &>/proc/1/fd/1" &
+      - name: Sync VMaaS repolist
+        run: |
+          ./scripts/setup_db.sh conf/repolist.json \
+          ${{ secrets.OPENSHIFT_REPOSCAN_URL }} \
+          ${{ secrets.OPENSHIFT_WEBAPP_URL }} \
+          ${{ secrets.VMAAS_BOT }}
+      - name: Run VMaaS integration tests
+        run: |
+          cat <<EOF > settings.local.yaml
+          default:
+            VULNERABILITY:
+              vmaas:
+                github:
+                  token: "${{ secrets.VMAAS_BOT }}"
+                hostname: "${{ secrets.OPENSHIFT_WEBAPP_URL }}"
+                auth_token: "${{ secrets.VMAAS_BOT }}"
+          EOF
+          docker run --name iqe --network host \
+            -v $(readlink -f settings.local.yaml):/iqe_settings/settings.local.yaml:z \
+            -e IQE_TESTS_LOCAL_CONF_PATH=/iqe_settings ${{ secrets.IQE_TESTS_IMAGE }} \
+            iqe tests plugin vulnerability -k 'vmaas' --html=report.html --self-contained-html
+      - name: Collect code-coverage
+        if: always()
+        run: |
+          webapp_pod="$(oc get pods | grep 'Running' | grep 'webapp' | awk '{print $1}')"
+          oc exec ${webapp_pod} -- pkill -sigint coverage
+          oc exec ${webapp_pod} -- coverage html --omit /usr/\\* -d /tmp/htmlcov
+          mkdir htmlcov
+          oc cp ${webapp_pod}:/tmp/htmlcov htmlcov
+          oc exec ${webapp_pod} -- bash -c 'main.py &>/proc/1/fd/1' &
+      - name: Get OpenShift logs
+        if: always()
+        run: |
+          oc project vmaas-qe
+          mkdir -p applogs/
+          PODS=$(oc get pods -o jsonpath='{range .items[*]}{.metadata.name}{"\\n"}')
+          for pod in $PODS; do
+              CONTAINERS=$(oc get pod $pod -o jsonpath='{range .spec.containers[*]}{.name}{"\\n"}' || echo "")
+              if [ -z "$CONTAINERS" ]; then
+                  echo "get logs: pod $pod not found"
+              fi;
+              for container in $CONTAINERS; do
+                  oc logs $pod -c $container > applogs/${pod}_${container}.log || echo "get logs: ${pod}_${container} failed."
+                  echo "Saved logs for $pod container $container"
+              done
+          done
+      - run: docker cp iqe:/iqe_venv/report.html .
+        if: always()
+      - name: Publish test results
+        uses: actions/upload-artifact@v1
+        if: always()
+        with:
+          name: test-report-openshift
+          path: report.html
+      - name: Publish coverage report
+        uses: actions/upload-artifact@v1
+        if: always()
+        with:
+          name: coverage-report
+          path: htmlcov
+      - name: Publish logs
+        uses: actions/upload-artifact@v1
+        if: always()
+        with:
+          name: openshift-logs
+          path: applogs
